#!/bin/bash

COUNT=0

version() {
    case $1 in
        nodesource )
            echo `node -e 'console.log(require("./package.json").engines.nodesource)'`
            ;;

        * )
            echo `node -e 'console.log(require("./package.json").version)'`
            ;;
    esac
}

debug() {
    make -s clean
    make -s build

    sudo ./debug --mode development $@
}

publish() {
    current=$(version)

    case $1 in
        stable | edge | bleeding )
            reprepro -b ../repo/debian includedeb $1 builds/hoobsd-$current-hoobs-amd64.deb
            reprepro -b ../repo/debian includedeb $1 builds/hoobsd-$current-hoobs-arm64.deb
            reprepro -b ../repo/debian includedeb $1 builds/hoobsd-$current-hoobs-armhf.deb
            ;;

        list )
            list $2
            ;;
    esac
}

list() {
    case $1 in
        stable )
            reprepro -b ../repo/debian list stable hoobsd
            ;;

        edge )
            reprepro -b ../repo/debian list edge hoobsd
            ;;

        bleeding )
            reprepro -b ../repo/debian list bleeding hoobsd
            ;;

        * )
            reprepro -b ../repo/debian list stable hoobsd
            reprepro -b ../repo/debian list edge hoobsd
            reprepro -b ../repo/debian list bleeding hoobsd
            ;;
    esac
}

image() {
    if [[ $COUNT -gt 0 ]] ; then
        echo "" >> build.log
    fi

    echo "$1 - $(date)" >> build.log
    echo "------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------" >> build.log

    make hoobsd-$1

    echo "------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------" >> build.log

    COUNT=$((COUNT+1))
}

build() {
    touch build.log
    truncate -s 0 build.log

    image arm64
    image armhf
    image amd64
}

case $1 in
    version )
        shift

        version $@
        ;;

    lint )
        make lint
        ;;

    debug )
        shift

        debug $@
        ;;

    build )
        build
        ;;

    publish )
        shift

        publish $@
        ;;

    clean )
        make clean
        ;;
esac
